name: ${project.artifactId}
main: work.xeltica.craft.otanoshimiplugin.OtanoshimiPlugin
version: ${project.version}
api-version: 1.16
softdepend:
  - Vault
commands:
  omikuji:
    description: おみくじを引きます。マイクラ内で1日に1回まで引けて、100クローバーかかります。
    usage: /omikuji
  respawn:
    description: メインワールドの初期スポーンに戻ります。
    usage: /respawn
  pvp:
    description: 現在のワールドのPvP設定を変更します。
    usage: /pvp <on/off>
    permission: otanoshimi.command.pvp
  signedit:
    description: 看板の指定行を編集します。
    usage: /signedit <行番号> <テキスト>
    permission: otanoshimi.command.signedit
  givetravelticket:
    description: トラベルチケットを授与します。
    usage: /givetravelticket <playerName> [type=NORMAL] [amount=1]
    permission: otanoshimi.command.givetravelticket
  report:
    description: 処罰GUIを表示します。
    usage: /report <playerName>
    permission: otanoshimi.command.report
permissions:
  otanoshimi.command.pvp:
    default: op
  otanoshimi.command.givetravelticket:
    default: op
  otanoshimi.command.signedit:
    default: true
  otanoshimi.command.report:
    default: op
