version: 2.1

jobs:
  build-develop:  
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - restore_cache:
          key: x-cache-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: x-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - store_artifacts:
          path: ~/project/target/XCore.jar
      - add_ssh_keys:
          fingerprints:
            - "d2:1b:72:bd:6c:b7:d6:ef:41:50:1c:73:dd:f0:84:bb"
      - run: echo 'dev.craft.xeltica.work,172.105.228.229 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPM+9SLKKCgxISLxKq4Px2HQ95x8LAOPLY4/xQSyusyDYYp6zY3VlIbOTwKrXSzRR1P5LgMc+oUA0k9pVWdqhnc=' >> ~/.ssh/known_hosts
      - run: sftp xeltica@dev.craft.xeltica.work:/srv/papermc/plugins \<< 'put ~/project/target/XCore.jar'
      - run: ssh xeltica@dev.craft.xeltica.work 'sh /srv/deploy-core.sh'
  build-master:  
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - restore_cache:
          key: x-cache-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: x-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - store_artifacts:
          path: ~/project/target/XCore.jar
      - add_ssh_keys:
          fingerprints:
            - "d2:1b:72:bd:6c:b7:d6:ef:41:50:1c:73:dd:f0:84:bb"
      - run: echo 'play.craft.xeltica.work,172.105.242.153 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPM+9SLKKCgxISLxKq4Px2HQ95x8LAOPLY4/xQSyusyDYYp6zY3VlIbOTwKrXSzRR1P5LgMc+oUA0k9pVWdqhnc=' >> ~/.ssh/known_hosts
      - run: sftp xeltica@play.craft.xeltica.work:/srv/papermc/plugins \<< 'put ~/project/target/XCore.jar'
      - run: ssh xeltica@play.craft.xeltica.work 'sh /srv/deploy-core.sh'

workflows:
  build: 
    jobs:
      - build-develop:
          filters:
            branches:
              only: 
                - develop
      - build-tag:
          filters:
            branches:
              only: 
                - master
